# Generated by Django 5.2.4 on 2025-12-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="user_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_responses",
                to="chat.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_comparison",
            field=models.BooleanField(default=False),
        ),
    ]
