# Generated by Django 5.2.4 on 2025-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_user_message_chatsession_is_comparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("bridge", "Bridge"),
                    ("baseline", "Baseline"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
