# Generated by Django 5.2.4 on 2025-12-28 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="user_message",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="is_comparison",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_type",
            field=models.CharField(
                choices=[("normal", "Normal Chat"), ("comparison", "Comparison Chat")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ComparisonTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("turn_number", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baseline_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_comparisons",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "bridge_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bridge_comparisons",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_turns",
                        to="chat.chatsession",
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_turns",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_number"],
            },
        ),
    ]
