# Generated by Django 5.2.4 on 2025-12-28 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatmessage_message_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("genz", "GenZ Mode"), ("parent", "Parent Mode")],
                        default="genz",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="New Comparison Session", max_length=200),
                ),
                ("session_key", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("turn_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="comparisonturn",
            name="baseline_thinking",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comparisonturn",
            name="bridge_thinking",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="baseline_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="bridge_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="user_message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="chat.comparisonsession",
            ),
        ),
    ]
