# Generated by Django 5.2.4 on 2025-12-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_comparisonsession_comparisonturn_baseline_thinking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonturn",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_turns",
                to="chat.chatsession",
            ),
        ),
        migrations.RemoveField(
            model_name="comparisonturn",
            name="baseline_thinking",
        ),
        migrations.RemoveField(
            model_name="comparisonturn",
            name="bridge_thinking",
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="baseline_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baseline_comparisons",
                to="chat.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="bridge_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bridge_comparisons",
                to="chat.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="comparisonturn",
            name="user_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_turns",
                to="chat.chatmessage",
            ),
        ),
        migrations.DeleteModel(
            name="ComparisonSession",
        ),
    ]
